# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

# Setup
title:               Leonardo Amorim
tagline:             'Electronics, Microcontrollers, FPGAs, Computer Programming and some useful stuff.'
description:         'Contents about electronics, computer programming and embedded systems'

url:                 https://leonardoaraujodf.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Leonardo Amorim
  url:               https://github.com/leonardoaraujodf
  email:             leonardoaraujodf@gmail.com

# Custom vars
version:             1.0.0
plugins: [jekyll-paginate]
