# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

# Setup
title:               Leonardo Amorim
tagline:             'Hi, my name is Leonardo, a electronic engineer at University of Brasilia, Brazil, and this blog is to show some useful stuff about electronics, computer programming, embedded systems, FPGAs and so on. Feel free to contact me and enjoy ;D'
description:         'Contents about electronics, computer programming, embedded systems and some useful stuff.'

# A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'

url:                 https://leonardoaraujodf.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Leonardo Amorim
  url:               https://github.com/leonardoaraujodf
  email:             leonardoaraujodf@gmail.com

# Custom vars
version:             1.0.0
plugins: [jekyll-paginate]
