title: Leonardo Amorim
description: Hi! My name is Leonardo Amorim, I'm an Electronic Engineer at University of Brasilia, Brazil, and this blog you can find tutorials and some other useful things about C, C++, VHDL, Microcontrollers, FPGAs and so on. 
show_downloads: true

baseurl: "/blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://leonardoaraujodf.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: Leonardo Amorim
image: /thumbnail-jumbo.png
twitter:
  username: leoaraujodf 

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
